#!/bin/bash
# set i to 9
i=9
while [ $i -lt 31 ]; do
	echo "No $i"
	gawk -f ~/Documentos/TG/Scripts/Throughput2007.awk ~/Documentos/TG/UDP/1Tr/"$i"UDP/AODV/"$i"UDP.tr >> AODV1TrThr.txt
	gawk -f ~/Documentos/TG/Scripts/e2edelayudp.awk ~/Documentos/TG/UDP/1Tr/"$i"UDP/AODV/"$i"UDP.tr >> AODV1TrDelay.txt
        gawk -f ~/Documentos/TG/Scripts/droppackets.awk ~/Documentos/TG/UDP/1Tr/"$i"UDP/AODV/"$i"UDP.tr >> AODV1TrDrop.txt
        gawk -f ~/Documentos/TG/Scripts/Throughput2007.awk ~/Documentos/TG/UDP/1Tr/"$i"UDP/DSR/"$i"UDP.tr >> DSR1TrThr.txt
        gawk -f ~/Documentos/TG/Scripts/e2edelayudp.awk ~/Documentos/TG/UDP/1Tr/"$i"UDP/DSR/"$i"UDP.tr >> DSR1TrDelay.txt
        gawk -f ~/Documentos/TG/Scripts/droppackets.awk ~/Documentos/TG/UDP/1Tr/"$i"UDP/DSR/"$i"UDP.tr >> DSR1TrDrop.txt
        gawk -f ~/Documentos/TG/Scripts/Throughput2007.awk ~/Documentos/TG/UDP/1Tr/"$i"UDP/WCETT/"$i"UDP.tr >> WCETT1TrThr.txt
        gawk -f ~/Documentos/TG/Scripts/e2edelayudp.awk ~/Documentos/TG/UDP/1Tr/"$i"UDP/WCETT/"$i"UDP.tr >> WCETT1TrDelay.txt
        gawk -f ~/Documentos/TG/Scripts/droppackets.awk ~/Documentos/TG/UDP/1Tr/"$i"UDP/WCETT/"$i"UDP.tr >> WCETT1TrDrop.txt

	let i=i+1;
done
